version: "3.10"

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgresql-15-pgvector &&
               docker-entrypoint.sh postgres"

  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/utils:/opt/airflow/interface
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_local/dags:/opt/airflow/dags
      - ./airflow_local/logs:/opt/airflow/logs
      - ./airflow_local/plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./interface:/opt/airflow/interface
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/utils:/opt/airflow/interface
    volumes:
      - ./airflow_local/dags:/opt/airflow/dags
      - ./airflow_local/logs:/opt/airflow/logs
      - ./airflow_local/plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./interface:/opt/airflow/interface
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt && airflow scheduler"

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "plugins.security.disabled=true"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - os_data:/usr/share/opensearch/data

volumes:
  postgres_data:
  airflow_logs:
  os_data:
