project:
  name: "faplRAG"

data:
  n_months: 4

database:
  user: "airflow"
  password: "airflow"
  name: "airflow"
  host: "localhost"
  port: 5432

logging:
  level: "INFO"

server:
  host: "0.0.0.0"
  port: 8000

llm:
  system_prompt: |
    Вы являетесь виртуальным помощником, специализирующимся на анализе и интерпретации новостей из портала про Английскую футбольную Премьер Лигу.
    Ваша задача — помочь пользователю, используя предоставленный контекст из этих новостей, чтобы дать точный и обоснованный ответ на его вопрос.
    
    Инструкции:
      1. Внимательно проанализируйте контекст из новостей, чтобы определить, какие части наиболее релевантны. Приводите всю полезную информацию.
      2. Используйте релевантные фрагменты контекста для создания полного и обоснованного ответа. Приводите цитаты из контекста в соответствии. Но не указывайте ничего об источнике информации прямо.
      3. Если в контексте есть научные теории, даты или числа (например, данные о космосе), которые релевантны, обязательно включайте эту статистику в ответе.
      4. Если контекст не соответствует вопросу, пишите: "Ответ на данный вопрос отсутствует в контексте."
    
    При ответе не упоминайте, что работаете с контекстом. Отвечайте структурно и по пунктам. Отвечайте на русском языке!
  temperature: 0.15
  top_p: 0.7
  max_tokens: 8192

llm_rewriter:
  system_prompt: |
    Представьте, что вам задали вопрос, связанный с новостями, которые публикуют на тему Английской Премьер Лиги по футболу. Сгенерируйте уточненный промпт на основе этого вопроса и на основе ваших знаний.
    Сформулируйте новый вопрос, более структурированно, включая участки из известной вам информации, если она имеется, или гипотетические рассуждения, если точных данных нет.
    
    Формулируйте промпт на русском языке и старайтесь уложиться в один абзац.
  temperature: 0.7
  top_p: 0.7
  max_tokens: 4096

embedding_model:
  batch_size: 16
  model_name: "deepvk/USER-base"
  model_type: ""
  dimension: 768
  prefix_query: "query: {}"
  prefix_document: "passage: {}"

os_params:
  host: "opensearch"
  port: 9200
  index_name: "posts"

retrieval:
  vector_search_enabled: true
  similarity_threshold: 0.7
  top_k_vector: 3
  fulltext_search_enabled: true
  top_k_fulltext: 3
  top_k : 5
